services:
  r2m-website:
    build:
      context: ./r2m-website
      args:
        - WEBSITE_URL=$FRONTEND_URL
        - BACKEND_NAME=$BACKEND_NAME
    networks:
      - r2m
  r2m:
    build: ./rusty-retro-messaging
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_NAME: ${BACKEND_NAME}
      SWITCHBOARD_IP: ${SWITCHBOARD_IP}
      SWITCHBOARD_PORT: ${SWITCHBOARD_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      USE_REGISTRATION_CODES: ${USE_REGISTRATION_CODES}
    depends_on:
      - r2m-db
    networks:
      - r2m
    ports:
      - 1863:1863
      - 1864:1864
  r2m-db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - r2m-db-data:/var/lib/mysql
    networks:
      - r2m

networks:
  r2m:
    driver: bridge

volumes:
  r2m-db-data: