CREATE TABLE IF NOT EXISTS users (
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   email VARCHAR(100) NOT NULL,
   password VARCHAR(100) NOT NULL,
   display_name VARCHAR(150) NOT NULL,
   puid BIGINT UNSIGNED NOT NULL,
   guid VARCHAR(50) NOT NULL,
   gtc VARCHAR(5) NOT NULL,
   blp VARCHAR(5) NOT NULL
);