CREATE TABLE users (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  display_name TEXT NOT NULL,
  puid BIGINT UNSIGNED NOT NULL,
  guid TEXT NOT NULL,
  gtc TEXT NOT NULL,
  blp TEXT NOT NULL
);