[package]
name = "rusty-retro-messaging"
version = "0.1.0"
edition = "2024"

[dependencies]
msnp-server = { path = "../msnp-server" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }